@api = http://localhost:5000

GET {{api}}/books/
################################
POST {{api}}/books/add
Content-Type: application/json

{
    "title" :"Julies Caesar",
    "pub_year": 2020,
    "description": "I came, I saw, I conquered."
}
################################